services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: face_swap
    ports:
      - "8000:8000"
    networks:
      - local_net
  demo:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.demo
    container_name: face_swap_demo
    ports:
      - "8501:8501"
    networks:
      - local_net
    environment:
      FACE_SWAP_SERVER: container

networks:
  local_net: