services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: "face_swap"
    ports:
      - "8000:8000"
    networks:
      - local_net

networks:
  local_net: